spring:
  config:
    activate:
      on-profile: prod
    import: application-secret.yml

  data:
    redis:
      host: redis
      port: 6379

server:
  port: 9091

app:
  clientUrl: https://j12d108.p.ssafy.io
  baseUrl: https://j12d108.p.ssafy.io
