spring:
  application:
    name: finbattle
  profiles:
    active: local
    group:
      local: local, secret
      prod: prod, secret

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: create
    show-sql: false

  #p6spy query logging
  decorator:
    datasource:
      p6spy:
        enable-logging: true

  data:
    redis:
      repositories:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

springdoc:
  swagger-ui:
    urls:
      - name: "FinBattle API"
        url: ${app.baseUrl}/v3/api-docs

application:
  version: 1.0.0
