spring:
  application:
    name: finbattle
  profiles:
    active: prod
    group:
      local: local, secret
      prod: prod, secret

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      repositories:
        enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

#springdoc:
#  api-docs:
#    enabled: true
#  swagger-ui:
#    enabled: true
#    path: /swagger-ui.html

springdoc:
  swagger-ui:
    urls:
      - name: "FinBattle API"
        url: "https://j12d108.p.ssafy.io/v3/api-docs"

application:
  version: 1.0.0